# Usa la imagen oficial de Nginx como base
FROM nginx:stable-alpine

# Copia nuestro archivo de configuración personalizado a la carpeta de configuraciones de Nginx
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf