# /home/nattancm/Proyectos secretos/GeoStab/Dockerfile.ui

# 1. Usa una imagen oficial de Python como base. 'slim' es una versión ligera.
FROM python:3.9-slim

# 2. Establece el directorio de trabajo dentro del contenedor.
WORKDIR /app

# 3. Copia solo el archivo de requerimientos primero para aprovechar el caché de Docker.
COPY requirements.txt .

# 4. Instala las dependencias de Python.
RUN pip install --no-cache-dir -r requirements.txt

# 5. Copia el código fuente de la aplicación de Streamlit.
#    Copia el archivo desde la raíz del proyecto al directorio de trabajo '/app' en el contenedor.
COPY streamlit_app.py .

# 6. Expone el puerto en el que Streamlit se ejecutará.
EXPOSE 8501

# El comando para ejecutar la app ya está en tu docker-compose.yml, por lo que un CMD aquí es opcional,
# pero es una buena práctica para la documentación y el uso independiente de la imagen.