# geostab/nginx/conf.d/geostab_challenge.conf

# Servidor temporal para la validación del desafío ACME
server {
    listen 80;
    server_name geostab.ddns.net;

    # Bloque para la validación HTTP-01
    location /.well-known/acme-challenge/ {
        # La raíz del documento debe coincidir con --webroot-path de Certbot.
        root /var/www/certbot; 
    }

    # Bloquea todo el tráfico que no sea el desafío para evitar redirecciones o exposiciones accidentales.
    location / {
        return 404 "Certbot Challenge Running";
    }
}